### ISSUE TITLE
Error on sonarqube-config pods

### ISSUE THREAD

**Issue by danielvaughan** [ibm-garage-cloud/toolkit-charts#123]
I am not sure if this is the correct repo but this is the error I am experiencing.

I am attempting to install the cloud native toolkit on an OpenShift cluster. This cluster is an IBM Cloud Satellite OpenShift 4.5.3 cluster. The pods for the sonarqube-config job are failing with the error:

```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/devops/.npm/_cacache
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 101:101 "/home/devops/.npm"

┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/devops/.config │
└──────────────────────────────────────────────────────────┘
bash: /home/devops/.npm-packages/bin/igc-web: No such file or directory
```

I think this is the correct repo but am not sure exactly how to resolve.

**Comment by mjperrins** [comment]
Hi David , which install method did you use and what style of cluster is this , is this on IBM Cloud or another type , also what storage class have you got in you cluster ?

**Comment by danielvaughan** [comment]
Hi Matt, it is an IBM Cloud Satellite cluster with dodgy storage. I am going to try it in IBM Cloud OpenShift proper to see if I get the same error.

**Comment by danielvaughan** [comment]
Install successful on an IBM Cloud 4.4.31. I am going to assume there is an issue to resolve for our satellite provisioning and work on that.

**Comment by mjperrins** [comment]
which install method did you , not seen sonar fail ever , but if you get a few mins today we could webex to have a look @seansund any comments ?

**Comment by mjperrins** [comment]
which environment for satellite ? will do some testing on satellite
